name: Zig CI

on:
  push:
    branches:
      - zig-version
  pull_request:
    branches:
      - zig-version

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: ${{ matrix.os }} (${{ matrix.sys-libs && 'system' || 'fetched' }} libs)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-14]
        sys-libs: [true, false]
        exclude:
          # Exclude macOS when using fetched libraries:
          # TODO FIX: ncurses configure complain about:
          # ../ncurses/tinfo/lib_baudrate.c:82:10: fatal error: 'sys/ttydev.h' file not found
          - os: macos-14
            sys-libs: false

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Zig
        id: setup-zig
        uses: mlugg/setup-zig@v2

      - name: Install dependencies (Ubuntu)
        if: matrix.sys-libs && startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses-dev libzstd-dev

      - name: Install dependencies (macOS)
        if: matrix.sys-libs && startsWith(matrix.os, 'macos')
        run: brew install ncurses zstd

      - name: Set Zig Build Flags
        shell: bash
        run: |
          FLAGS="-Doptimize=ReleaseSafe -Dpie"
          if [ "${{ matrix.sys-libs }}" = "true" ]; then
            FLAGS+=" -fsys=ncurses -fsys=zstd"
          else
            FLAGS+=" -fno-sys=ncurses -fno-sys=zstd"
          fi
          echo "ZIG_FLAGS=$FLAGS" >> $GITHUB_ENV

      - name: Build
        run: zig build ${{ env.ZIG_FLAGS }}

      - name: Verify JSON Export
        shell: bash
        run: |
          # Use src/ folder content
          # to keep the export small for job summary
          ./zig-out/bin/ncdu ./src -o export.json
          echo "### Scan Export (src/)" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          cat export.json >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Run Tests
        if: always() && steps.setup-zig.outcome == 'success'
        run: zig build test ${{ env.ZIG_FLAGS }}
